# SPDX-FileCopyrightText: 2023 ash_events contributors <https://github.com/ash-project/ash_events/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshEvents.Events.Validations.ReplayOnly do
  @moduledoc """
  Rejects any invocation that does not originate from event replay.

  AshEvents generates a companion update action for every upsert-capable
  create action so that replay can apply the recorded state onto an existing
  record. That action skips the source action's changes and validations and
  does not write an event, so it must never be reachable outside of replay.

  The replay runner marks every changeset it builds with
  `ash_events_replay?: true` in the changeset context. This validation fails
  when that marker is absent.
  """
  use Ash.Resource.Validation

  @impl true
  def validate(changeset, _opts, _context) do
    if Map.get(changeset.context, :ash_events_replay?) do
      :ok
    else
      {:error,
       "action #{inspect(changeset.action.name)} is auto-generated by AshEvents for event replay and cannot be called directly"}
    end
  end

  @impl true
  def atomic(changeset, opts, context) do
    validate(changeset, opts, context)
  end
end
