# SPDX-FileCopyrightText: 2023 ash_events contributors <https://github.com/ash-project/ash_events/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshEvents.TestRepo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orgs_cloaked, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:encrypted_name, :binary, null: false)
    end

    create table(:events_cloaked, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:record_id, :uuid, null: false)
      add(:version, :bigint, null: false, default: 1)
      add(:encrypted_metadata, :binary, null: false)
      add(:encrypted_data, :binary, null: false)
      add(:occurred_at, :utc_datetime_usec, null: false)
      add(:resource, :text, null: false)
      add(:action, :text, null: false)
      add(:action_type, :text, null: false)
      add(:user_id, :uuid)
      add(:system_actor, :text)
    end
  end

  def down do
    drop(table(:events_cloaked))

    drop(table(:orgs_cloaked))
  end
end
