# SPDX-FileCopyrightText: 2024 Torkild G. Kjevik
#
# SPDX-License-Identifier: MIT

defmodule AshEvents.TestRepo.Migrations.AddUserWithAutoAttrs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users_with_auto_attrs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :text, null: false)
      add(:name, :text, null: false)
      add(:status, :text, null: false, default: "active")
      add(:slug, :text, null: false)
    end
  end

  def down do
    drop(table(:users_with_auto_attrs))
  end
end
