defmodule AshEvents.TestRepo.Migrations.AddRoutedUserHashedPassword do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:routed_users) do
      add(:hashed_password, :text, null: false)
    end
  end

  def down do
    alter table(:routed_users) do
      remove(:hashed_password)
    end
  end
end
