# SPDX-FileCopyrightText: 2024 Torkild G. Kjevik
#
# SPDX-License-Identifier: MIT

defmodule AshEvents.TestRepo.Migrations.AddUploadsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:uploads, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:file_name, :text, null: false)
      add(:s3_key_formatted, :text)
      add(:state, :text, null: false, default: "skipped")
    end

    create unique_index(:uploads, [:file_name], name: "uploads_unique_file_name_index")
  end

  def down do
    drop_if_exists(unique_index(:uploads, [:file_name], name: "uploads_unique_file_name_index"))

    drop(table(:uploads))
  end
end
