defmodule AshEvents.TestRepo.Migrations.AddUsersEmbedded do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users_embedded, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:email, :text, null: false)
      add(:given_name, :text, null: false)
      add(:family_name, :text, null: false)
      add(:address, :map)
      add(:other_addresses, {:array, :map})
    end
  end

  def down do
    drop(table(:users_embedded))
  end
end
