# SPDX-FileCopyrightText: 2023 ash_events contributors <https://github.com/ash-project/ash_events/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshEvents.TestRepo.Migrations.MakeUserNameNilable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify(:hashed_password, :text, null: true)
      modify(:family_name, :text, null: true)
      modify(:given_name, :text, null: true)
    end
  end

  def down do
    alter table(:users) do
      modify(:given_name, :text, null: false)
      modify(:family_name, :text, null: false)
      modify(:hashed_password, :text, null: false)
    end
  end
end
