# SPDX-FileCopyrightText: 2023 ash_events contributors <https://github.com/ash-project/ash_events/graphs.contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshEvents.TestRepo.Migrations.AddChangedAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events_uuidv7) do
      add(:changed_attributes, :map, null: false, default: %{})
    end

    alter table(:events_state_machine) do
      add(:changed_attributes, :map, null: false, default: %{})
    end

    alter table(:events_cloaked) do
      add(:encrypted_changed_attributes, :binary, null: false)
    end

    alter table(:events) do
      add(:changed_attributes, :map, null: false, default: %{})
    end
  end

  def down do
    alter table(:events) do
      remove(:changed_attributes)
    end

    alter table(:events_cloaked) do
      remove(:encrypted_changed_attributes)
    end

    alter table(:events_state_machine) do
      remove(:changed_attributes)
    end

    alter table(:events_uuidv7) do
      remove(:changed_attributes)
    end
  end
end
