# SPDX-FileCopyrightText: 2024 Torkild G. Kjevik
#
# SPDX-License-Identifier: MIT

defmodule AshEvents.TestRepo.Migrations.AddSensitiveFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add(:api_key_hash, :binary)
      add(:sensitive_token, :binary)
      add(:binary_keys, {:array, :binary})
    end

    alter table(:orgs_cloaked) do
      add(:secret_key, :text)
      add(:api_token, :text)
    end

    alter table(:events_uuidv7) do
      add(:data_field_encoders, :map, null: false, default: %{})
      add(:changed_attributes_field_encoders, :map, null: false, default: %{})
    end

    alter table(:events_state_machine) do
      add(:data_field_encoders, :map, null: false, default: %{})
      add(:changed_attributes_field_encoders, :map, null: false, default: %{})
    end

    alter table(:events_cloaked) do
      add(:data_field_encoders, :map, null: false, default: %{})
      add(:changed_attributes_field_encoders, :map, null: false, default: %{})
    end

    alter table(:events) do
      add(:data_field_encoders, :map, null: false, default: %{})
      add(:changed_attributes_field_encoders, :map, null: false, default: %{})
    end
  end

  def down do
    alter table(:events) do
      remove(:changed_attributes_field_encoders)
      remove(:data_field_encoders)
    end

    alter table(:events_cloaked) do
      remove(:changed_attributes_field_encoders)
      remove(:data_field_encoders)
    end

    alter table(:events_state_machine) do
      remove(:changed_attributes_field_encoders)
      remove(:data_field_encoders)
    end

    alter table(:events_uuidv7) do
      remove(:changed_attributes_field_encoders)
      remove(:data_field_encoders)
    end

    alter table(:orgs_cloaked) do
      remove(:api_token)
      remove(:secret_key)
    end

    alter table(:users) do
      remove(:binary_keys)
      remove(:sensitive_token)
      remove(:api_key_hash)
    end
  end
end
