# SPDX-FileCopyrightText: 2024 Torkild G. Kjevik
#
# SPDX-License-Identifier: MIT

defmodule AshEvents.TestRepo.Migrations.SetHashedPasswordAsNonNilable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:routed_users) do
      modify(:hashed_password, :text, null: true)
    end
  end

  def down do
    alter table(:routed_users) do
      modify(:hashed_password, :text, null: false)
    end
  end
end
