# SPDX-FileCopyrightText: 2023 ash_events contributors <https://github.com/ash-project/ash_events/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshEvents.TestRepo.Migrations.AddCommentsTagsArticleTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:name, :text, null: false)
    end

    create table(:comments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:body, :text, null: false)

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "comments_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:article_tags, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :article_id,
        references(:articles,
          column: :id,
          name: "article_tags_article_id_fkey",
          type: :uuid,
          prefix: "public"
        ), primary_key: true, null: false)

      add(
        :tag_id,
        references(:tags,
          column: :id,
          name: "article_tags_tag_id_fkey",
          type: :uuid,
          prefix: "public"
        ), primary_key: true, null: false)
    end
  end

  def down do
    drop(constraint(:article_tags, "article_tags_article_id_fkey"))

    drop(constraint(:article_tags, "article_tags_tag_id_fkey"))

    drop(table(:article_tags))

    drop(constraint(:comments, "comments_user_id_fkey"))

    drop(table(:comments))

    drop(table(:tags))
  end
end
