defmodule AshEvents.TestRepo.Migrations.AddUsersNonWritableId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users_non_writable_id, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :text, null: false)
      add(:name, :text, null: false)
    end

    alter table(:events_uuidv7) do
      remove(:changed_attributes_field_encoders)
      remove(:data_field_encoders)
    end

    alter table(:events_state_machine) do
      remove(:changed_attributes_field_encoders)
      remove(:data_field_encoders)
    end

    alter table(:events_cloaked) do
      remove(:changed_attributes_field_encoders)
      remove(:data_field_encoders)
    end

    alter table(:events) do
      remove(:changed_attributes_field_encoders)
      remove(:data_field_encoders)
    end
  end

  def down do
    alter table(:events) do
      add(:data_field_encoders, :map, null: false, default: %{})
      add(:changed_attributes_field_encoders, :map, null: false, default: %{})
    end

    alter table(:events_cloaked) do
      add(:data_field_encoders, :map, null: false, default: %{})
      add(:changed_attributes_field_encoders, :map, null: false, default: %{})
    end

    alter table(:events_state_machine) do
      add(:data_field_encoders, :map, null: false, default: %{})
      add(:changed_attributes_field_encoders, :map, null: false, default: %{})
    end

    alter table(:events_uuidv7) do
      add(:data_field_encoders, :map, null: false, default: %{})
      add(:changed_attributes_field_encoders, :map, null: false, default: %{})
    end

    drop(table(:users_non_writable_id))
  end
end
