# SPDX-FileCopyrightText: 2023 ash_events contributors <https://github.com/ash-project/ash_events/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshEvents.TestRepo.Migrations.UpdateArticleTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint("article_tags", "article_tags_pkey"))

    alter table(:article_tags) do
      modify(:tag_id, :uuid)
      modify(:article_id, :uuid)
    end

    execute("ALTER TABLE \"article_tags\" ADD PRIMARY KEY (id)")
  end

  def down do
    alter table(:article_tags) do
      modify(:article_id, :uuid)
      modify(:tag_id, :uuid)
    end

    execute("ALTER TABLE \"article_tags\" DROP constraint article_tags_pkey")

    execute("ALTER TABLE \"article_tags\" ADD PRIMARY KEY (id, article_id, tag_id)")
  end
end
